# scrutinizer-ci.com configuration
imports:
    - python
tools:
    external_code_coverage:
        runs: 6
        timeout: 3600
    pylint:
        python_version: 2
        config_file: '.pylintrc'
checks:
    python:
        code_rating: true
        duplicate_code: true
before_commands:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
