language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
# commands to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=odorik
after_script:
  - codecov
  - python-codacy-coverage
