#!/bin/sh
set -e

if [ -z "$1" ] ; then
    echo 'Usage: ./scripts/set-version VERSION'
    exit 1
fi

sed -i "s/^__version__ =.*/__version__ = '$1'/" odorik/__init__.py

# Update docs/changes.md
tmp=`mktemp`
cp docs/news.rst $tmp
cat > docs/news.rst <<EOT
Changes
=======

$1
---

EOT
sed '1D;2D;3D' >> docs/news.rst < $tmp
rm $tmp

git commit -m "Setting version to $1" odorik/__init__.py docs/news.rst
